"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 19:22:05.581725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=40), nullable=False),
    sa.Column('corrected_severity', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analyst', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyst_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_feedback_incident_id'), ['incident_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_ts'), ['ts'], unique=False)

    op.create_table('decision_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_hash', 'model', name='uq_decision_hash_model')
    )
    with op.batch_alter_table('decision_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_runs_evidence_hash'), ['evidence_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_runs_incident_id'), ['incident_id'], unique=False)

    op.create_table('entities',
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=260), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.String(length=40), nullable=True),
    sa.Column('last_seen', sa.String(length=40), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('ix_entities_type_value', ['type', 'value'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('runtime_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_run_id'), ['run_id'], unique=False)

    op.create_table('incidents',
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('correlation_confidence', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('chain_strength', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('anomaly_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deterministic_risk', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('primary_entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('top_alert_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mitre_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('template_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analyst_verdict', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('incident_id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_evidence_hash'), ['evidence_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_rank'), ['rank'], unique=False)
        batch_op.create_index('ix_incidents_risk_status', ['risk_score', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_run_id'), ['run_id'], unique=False)

    op.create_table('ingest_batches',
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('received', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('llm_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attempts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_runs_evidence_hash'), ['evidence_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_runs_incident_id'), ['incident_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timings_ms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('triage_trials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('vendor', sa.String(length=80), nullable=False),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user', sa.String(length=200), nullable=True),
    sa.Column('user_display', sa.String(length=200), nullable=True),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('host_display', sa.String(length=200), nullable=True),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('src_ip_internal', sa.Boolean(), nullable=True),
    sa.Column('dst_ip', sa.String(length=64), nullable=True),
    sa.Column('dst_ip_internal', sa.Boolean(), nullable=True),
    sa.Column('process', sa.String(length=200), nullable=True),
    sa.Column('resource', sa.String(length=200), nullable=True),
    sa.Column('asset_criticality', sa.Integer(), nullable=False),
    sa.Column('user_privilege', sa.Integer(), nullable=False),
    sa.Column('raw_event_ref', sa.String(length=200), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('rule_anomaly_score', sa.Float(), nullable=True),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['ingest_batches.batch_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('alert_id'),
    sa.UniqueConstraint('content_hash')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_src_ip'), ['src_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user'), ['user'], unique=False)

    op.create_table('attack_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.String(length=40), nullable=False),
    sa.Column('last_seen', sa.String(length=40), nullable=False),
    sa.Column('alert_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('alert_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attack_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attack_stages_incident_id'), ['incident_id'], unique=False)

    op.create_table('incident_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=260), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.String(length=40), nullable=True),
    sa.Column('last_seen', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_entities_incident_id'), ['incident_id'], unique=False)

    op.create_table('incident_mitre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tactics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_alert_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mapping_reason', sa.Text(), nullable=False),
    sa.Column('attack_catalog_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_mitre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_mitre_incident_id'), ['incident_id'], unique=False)

    op.create_table('alert_entities',
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'entity_key', 'role')
    )
    op.create_table('incident_alerts',
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('edge_score', sa.Float(), nullable=False),
    sa.Column('linked_alert_id', sa.String(length=64), nullable=True),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'alert_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_alerts')
    op.drop_table('alert_entities')
    with op.batch_alter_table('incident_mitre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_mitre_incident_id'))

    op.drop_table('incident_mitre')
    with op.batch_alter_table('incident_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_entities_incident_id'))

    op.drop_table('incident_entities')
    with op.batch_alter_table('attack_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attack_stages_incident_id'))

    op.drop_table('attack_stages')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user'))
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))
        batch_op.drop_index(batch_op.f('ix_alerts_src_ip'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_host'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    op.drop_table('triage_trials')
    op.drop_table('pipeline_runs')
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_runs_incident_id'))
        batch_op.drop_index(batch_op.f('ix_llm_runs_evidence_hash'))

    op.drop_table('llm_runs')
    op.drop_table('ingest_batches')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_run_id'))
        batch_op.drop_index('ix_incidents_risk_status')
        batch_op.drop_index(batch_op.f('ix_incidents_rank'))
        batch_op.drop_index(batch_op.f('ix_incidents_evidence_hash'))

    op.drop_table('incidents')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_run_id'))

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_type_value')

    op.drop_table('entities')
    with op.batch_alter_table('decision_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_runs_incident_id'))
        batch_op.drop_index(batch_op.f('ix_decision_runs_evidence_hash'))

    op.drop_table('decision_runs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_ts'))

    op.drop_table('audit_events')
    with op.batch_alter_table('analyst_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_feedback_incident_id'))

    op.drop_table('analyst_feedback')
    # ### end Alembic commands ###
